### ISSUE TITLE
Can't get into DFU mode.

### ISSUE THREAD

**Issue by nebelgrau77** [mcauser/WEACT_F411CEU6#4]
My board is a newer v2.0. I can't get it to work in DFU mode, following all the steps described. DFU-util shows nothing. The board itself works for sure, it can be flashed using SWD with ST-Link. Is there an alternative way of uploading MicroPython firmware, like with SWD? There's clearly some problem with the boot selection, that I don't know how to solve.

**Comment by SuperThunder** [comment]
What OS are you using?

If you do:
- Plug board into USB
- Hold NRST
- Hold BOOT0
- Release NRST
- Release BOOT0

What happens? Any USB devices detected?

You can indeed upload with SWD. It's just a hex / bin file that says what bytes the flash should have. I use STM32CubeProgrammer and upload the generated hex file.

**Comment by nebelgrau77** [comment]
My OS is Kubuntu 19.10 Eoan Ermine. 

The trick with holding and then releasing NRST and BOOT0 doesn't work, dfu-util -l just displays the info about the dfu-util, version 0.9. 

It doesn't matter if PA9 and PA10 are shorted as indicated.

Not sure if it could be a HW board problem, because I could never get it to show up through serial, either, I mean with FTDI breakout board connected and the stm32flash tool. With other boards, like blue pill or the F407VET "tile" it works without any problems if you set the jumpers for bootloader mode. Here it just won't. 

OK, so what should I upload via SWD, is it the firmware.hex file?

**Comment by SuperThunder** [comment]
Does anything new show up in 'lsusb' after doing the NRST - BOOT0 sequence?

Yep, you can upload the firmware.hex file through SWD.

**Comment by nebelgrau77** [comment]
Nope, nothing shows up, I checked that.

But I did upload MicroPython, using ST Link and OpenOCD, following this article (could be useful if someone else has a similar problem): 

https://www.carminenoviello.com/2015/06/03/running-micropyton-stm32nucleo-f4/
